name: Publish package to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Publish package
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          maven-repo-server-id: github
          maven-repo-server-username: ${{ github.actor }}
          maven-repo-server-password: ${{ github.token }}

          gpg-enabled: "false"

          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@example.com"

          access-token: ${{ secrets.GITHUB_TOKEN }}
